language: java
sudo: false

jdk:
  - openjdk11

branches:
  only:
    - master
    - main
    - /^fcrepo-*/

script:
  - mvn install
  - unzip -d target/zipout target/fcrepo-build-tools-*.jar
  - test "0" == $([ -f target/zipout/fcrepo-checkstyle/checkstyle.xml ] && echo "0" || echo "1")
  - test "0" == $([ -f target/zipout/fcrepo-checkstyle/checkstyle-suppressions.xml ] && echo "0" || echo "1")
  - test "0" == $([ -f target/zipout/fcrepo-license/LICENSE_HEADER.txt ] && echo "0" || echo "1")
  - mvn javadoc:jar
  - mvn javadoc:test-aggregate


notifications:
  irc: "irc.freenode.org#fcrepo"
  email:
    - fedora-tech@googlegroups.com
